/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ApiCoachChatRouteImport } from './routes/api/coach-chat'
import { Route as ShellCoachIndexRouteImport } from './routes/_shell.coach.index'
import { Route as ShellCoachThreadIdRouteImport } from './routes/_shell.coach.$threadId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ApiCoachChatRoute = ApiCoachChatRouteImport.update({
  id: '/api/coach-chat',
  path: '/api/coach-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCoachIndexRoute = ShellCoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCoachThreadIdRoute = ShellCoachThreadIdRouteImport.update({
  id: '/coach/$threadId',
  path: '/coach/$threadId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/coach/$threadId': typeof ShellCoachThreadIdRoute
  '/coach/': typeof ShellCoachIndexRoute
}
export interface FileRoutesByTo {
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/': typeof ShellIndexRoute
  '/coach/$threadId': typeof ShellCoachThreadIdRoute
  '/coach': typeof ShellCoachIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/coach/$threadId': typeof ShellCoachThreadIdRoute
  '/_shell/coach/': typeof ShellCoachIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/coach-chat' | '/coach/$threadId' | '/coach/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/coach-chat' | '/' | '/coach/$threadId' | '/coach'
  id:
    | '__root__'
    | '/_shell'
    | '/api/coach-chat'
    | '/_shell/'
    | '/_shell/coach/$threadId'
    | '/_shell/coach/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  ApiCoachChatRoute: typeof ApiCoachChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/coach-chat': {
      id: '/api/coach-chat'
      path: '/api/coach-chat'
      fullPath: '/api/coach-chat'
      preLoaderRoute: typeof ApiCoachChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/coach/': {
      id: '/_shell/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof ShellCoachIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/coach/$threadId': {
      id: '/_shell/coach/$threadId'
      path: '/coach/$threadId'
      fullPath: '/coach/$threadId'
      preLoaderRoute: typeof ShellCoachThreadIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellCoachThreadIdRoute: typeof ShellCoachThreadIdRoute
  ShellCoachIndexRoute: typeof ShellCoachIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellCoachThreadIdRoute: ShellCoachThreadIdRoute,
  ShellCoachIndexRoute: ShellCoachIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ApiCoachChatRoute: ApiCoachChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
